apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pong-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/urgyan-balint/prereq
    targetRevision: HEAD
    path: charts/pong-app
    helm:
      valueFiles:
        - values.yaml
        - ../../argocd/cluster-overrides/pong-values-clusterB.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true